version: 2
jobs:
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: dialogflow-query-checker
          command: bin/dialogflow-query-checker run connpass_query_test.yml
workflows:
  version: 2
  test:
    jobs:
      - test
