version: 2
jobs:
  test:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Install root-ca
          command: apt-get install ca-certificates
      - checkout
      - run:
          name: dialogflow-query-checker
          command: bin/dialogflow-query-checker run connpass_query_test.yml
workflows:
  version: 2
  test:
    jobs:
      - test
